// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protocol.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ClientServerWithJava.Networking {

  /// <summary>Holder for reflection information generated from Protocol.proto</summary>
  public static partial class ProtocolReflection {

    #region Descriptor
    /// <summary>File descriptor for Protocol.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtocolReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5Qcm90b2NvbC5wcm90bxIFcHJvdG8iKQoHVXNlckRUTxIMCgRuYW1lGAEg",
            "ASgJEhAKCHBhc3N3b3JkGAIgASgJInEKCE1hdGNoRFRPEgoKAmlkGAEgASgF",
            "EgwKBHR5cGUYAiABKAkSFgoOYXZhaWxhYmxlU2VhdHMYAyABKAUSDwoHdGVh",
            "bTFJRBgEIAEoBRIPCgd0ZWFtMklEGAUgASgFEhEKCXNlYXRQcmljZRgGIAEo",
            "BSJaCg1CdXlUaWNrZXRzRFRPEg8KB21hdGNoSUQYASABKAUSDQoFcHJpY2UY",
            "AiABKAUSEgoKY2xpZW50TmFtZRgDIAEoCRIVCg1udW1iZXJPZlNlYXRzGAQg",
            "ASgFIqwCCgdSZXF1ZXN0EjAKDHJlcXVlc3RfdHlwZRgBIAEoDjIaLnByb3Rv",
            "LlJlcXVlc3QuUmVxdWVzdFR5cGUSIQoHdXNlcmR0bxgCIAEoCzIOLnByb3Rv",
            "LlVzZXJEVE9IABISCgh1c2VybmFtZRgDIAEoCUgAEhAKBmZpbHRydRgEIAEo",
            "CUgAEhAKBmlkVXNlchgFIAEoBUgAEikKCXRpY2tldGR0bxgGIAEoCzIULnBy",
            "b3RvLkJ1eVRpY2tldHNEVE9IACJhCgtSZXF1ZXN0VHlwZRIJCgVMT0dJThAA",
            "EgoKBkxPR09VVBABEgoKBlNJR05VUBACEg8KC0dFVF9NQVRDSEVTEAMSDwoL",
            "QlVZX1RJQ0tFVFMQBBINCglHRVRfTUFUQ0gQBUIGCgRkYXRhIvIBCghSZXNw",
            "b25zZRIzCg1yZXNwb25zZV90eXBlGAEgASgOMhwucHJvdG8uUmVzcG9uc2Uu",
            "UmVzcG9uc2VUeXBlEg0KBWVycm9yGAIgASgJEh8KB3VzZXJkdG8YAyABKAsy",
            "Di5wcm90by5Vc2VyRFRPEiEKCG1hdGNoZHRvGAQgASgLMg8ucHJvdG8uTWF0",
            "Y2hEVE8SDwoHbWF0Y2hlcxgFIAMoCSJNCgxSZXNwb25zZVR5cGUSBgoCT0sQ",
            "ABIJCgVFUlJPUhABEgoKBlVQREFURRACEg8KC0dFVF9NQVRDSEVTEAMSDQoJ",
            "R0VUX01BVENIEARCIqoCH0NsaWVudFNlcnZlcldpdGhKYXZhLk5ldHdvcmtp",
            "bmdiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ClientServerWithJava.Networking.UserDTO), global::ClientServerWithJava.Networking.UserDTO.Parser, new[]{ "Name", "Password" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ClientServerWithJava.Networking.MatchDTO), global::ClientServerWithJava.Networking.MatchDTO.Parser, new[]{ "Id", "Type", "AvailableSeats", "Team1ID", "Team2ID", "SeatPrice" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ClientServerWithJava.Networking.BuyTicketsDTO), global::ClientServerWithJava.Networking.BuyTicketsDTO.Parser, new[]{ "MatchID", "Price", "ClientName", "NumberOfSeats" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ClientServerWithJava.Networking.Request), global::ClientServerWithJava.Networking.Request.Parser, new[]{ "RequestType", "Userdto", "Username", "Filtru", "IdUser", "Ticketdto" }, new[]{ "Data" }, new[]{ typeof(global::ClientServerWithJava.Networking.Request.Types.RequestType) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ClientServerWithJava.Networking.Response), global::ClientServerWithJava.Networking.Response.Parser, new[]{ "ResponseType", "Error", "Userdto", "Matchdto", "Matches" }, null, new[]{ typeof(global::ClientServerWithJava.Networking.Response.Types.ResponseType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UserDTO : pb::IMessage<UserDTO>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UserDTO> _parser = new pb::MessageParser<UserDTO>(() => new UserDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UserDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ClientServerWithJava.Networking.ProtocolReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserDTO(UserDTO other) : this() {
      name_ = other.name_;
      password_ = other.password_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserDTO Clone() {
      return new UserDTO(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UserDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UserDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Password != other.Password) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UserDTO other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MatchDTO : pb::IMessage<MatchDTO>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MatchDTO> _parser = new pb::MessageParser<MatchDTO>(() => new MatchDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MatchDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ClientServerWithJava.Networking.ProtocolReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MatchDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MatchDTO(MatchDTO other) : this() {
      id_ = other.id_;
      type_ = other.type_;
      availableSeats_ = other.availableSeats_;
      team1ID_ = other.team1ID_;
      team2ID_ = other.team2ID_;
      seatPrice_ = other.seatPrice_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MatchDTO Clone() {
      return new MatchDTO(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 2;
    private string type_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Type {
      get { return type_; }
      set {
        type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "availableSeats" field.</summary>
    public const int AvailableSeatsFieldNumber = 3;
    private int availableSeats_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AvailableSeats {
      get { return availableSeats_; }
      set {
        availableSeats_ = value;
      }
    }

    /// <summary>Field number for the "team1ID" field.</summary>
    public const int Team1IDFieldNumber = 4;
    private int team1ID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Team1ID {
      get { return team1ID_; }
      set {
        team1ID_ = value;
      }
    }

    /// <summary>Field number for the "team2ID" field.</summary>
    public const int Team2IDFieldNumber = 5;
    private int team2ID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Team2ID {
      get { return team2ID_; }
      set {
        team2ID_ = value;
      }
    }

    /// <summary>Field number for the "seatPrice" field.</summary>
    public const int SeatPriceFieldNumber = 6;
    private int seatPrice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SeatPrice {
      get { return seatPrice_; }
      set {
        seatPrice_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MatchDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MatchDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Type != other.Type) return false;
      if (AvailableSeats != other.AvailableSeats) return false;
      if (Team1ID != other.Team1ID) return false;
      if (Team2ID != other.Team2ID) return false;
      if (SeatPrice != other.SeatPrice) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Type.Length != 0) hash ^= Type.GetHashCode();
      if (AvailableSeats != 0) hash ^= AvailableSeats.GetHashCode();
      if (Team1ID != 0) hash ^= Team1ID.GetHashCode();
      if (Team2ID != 0) hash ^= Team2ID.GetHashCode();
      if (SeatPrice != 0) hash ^= SeatPrice.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Type.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Type);
      }
      if (AvailableSeats != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(AvailableSeats);
      }
      if (Team1ID != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Team1ID);
      }
      if (Team2ID != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Team2ID);
      }
      if (SeatPrice != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(SeatPrice);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Type.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Type);
      }
      if (AvailableSeats != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(AvailableSeats);
      }
      if (Team1ID != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Team1ID);
      }
      if (Team2ID != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Team2ID);
      }
      if (SeatPrice != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(SeatPrice);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Type.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Type);
      }
      if (AvailableSeats != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AvailableSeats);
      }
      if (Team1ID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Team1ID);
      }
      if (Team2ID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Team2ID);
      }
      if (SeatPrice != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SeatPrice);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MatchDTO other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Type.Length != 0) {
        Type = other.Type;
      }
      if (other.AvailableSeats != 0) {
        AvailableSeats = other.AvailableSeats;
      }
      if (other.Team1ID != 0) {
        Team1ID = other.Team1ID;
      }
      if (other.Team2ID != 0) {
        Team2ID = other.Team2ID;
      }
      if (other.SeatPrice != 0) {
        SeatPrice = other.SeatPrice;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Type = input.ReadString();
            break;
          }
          case 24: {
            AvailableSeats = input.ReadInt32();
            break;
          }
          case 32: {
            Team1ID = input.ReadInt32();
            break;
          }
          case 40: {
            Team2ID = input.ReadInt32();
            break;
          }
          case 48: {
            SeatPrice = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Type = input.ReadString();
            break;
          }
          case 24: {
            AvailableSeats = input.ReadInt32();
            break;
          }
          case 32: {
            Team1ID = input.ReadInt32();
            break;
          }
          case 40: {
            Team2ID = input.ReadInt32();
            break;
          }
          case 48: {
            SeatPrice = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BuyTicketsDTO : pb::IMessage<BuyTicketsDTO>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BuyTicketsDTO> _parser = new pb::MessageParser<BuyTicketsDTO>(() => new BuyTicketsDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BuyTicketsDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ClientServerWithJava.Networking.ProtocolReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BuyTicketsDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BuyTicketsDTO(BuyTicketsDTO other) : this() {
      matchID_ = other.matchID_;
      price_ = other.price_;
      clientName_ = other.clientName_;
      numberOfSeats_ = other.numberOfSeats_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BuyTicketsDTO Clone() {
      return new BuyTicketsDTO(this);
    }

    /// <summary>Field number for the "matchID" field.</summary>
    public const int MatchIDFieldNumber = 1;
    private int matchID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MatchID {
      get { return matchID_; }
      set {
        matchID_ = value;
      }
    }

    /// <summary>Field number for the "price" field.</summary>
    public const int PriceFieldNumber = 2;
    private int price_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Price {
      get { return price_; }
      set {
        price_ = value;
      }
    }

    /// <summary>Field number for the "clientName" field.</summary>
    public const int ClientNameFieldNumber = 3;
    private string clientName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientName {
      get { return clientName_; }
      set {
        clientName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "numberOfSeats" field.</summary>
    public const int NumberOfSeatsFieldNumber = 4;
    private int numberOfSeats_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumberOfSeats {
      get { return numberOfSeats_; }
      set {
        numberOfSeats_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BuyTicketsDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BuyTicketsDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MatchID != other.MatchID) return false;
      if (Price != other.Price) return false;
      if (ClientName != other.ClientName) return false;
      if (NumberOfSeats != other.NumberOfSeats) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MatchID != 0) hash ^= MatchID.GetHashCode();
      if (Price != 0) hash ^= Price.GetHashCode();
      if (ClientName.Length != 0) hash ^= ClientName.GetHashCode();
      if (NumberOfSeats != 0) hash ^= NumberOfSeats.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MatchID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MatchID);
      }
      if (Price != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Price);
      }
      if (ClientName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ClientName);
      }
      if (NumberOfSeats != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(NumberOfSeats);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MatchID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MatchID);
      }
      if (Price != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Price);
      }
      if (ClientName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ClientName);
      }
      if (NumberOfSeats != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(NumberOfSeats);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MatchID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MatchID);
      }
      if (Price != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Price);
      }
      if (ClientName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientName);
      }
      if (NumberOfSeats != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumberOfSeats);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BuyTicketsDTO other) {
      if (other == null) {
        return;
      }
      if (other.MatchID != 0) {
        MatchID = other.MatchID;
      }
      if (other.Price != 0) {
        Price = other.Price;
      }
      if (other.ClientName.Length != 0) {
        ClientName = other.ClientName;
      }
      if (other.NumberOfSeats != 0) {
        NumberOfSeats = other.NumberOfSeats;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MatchID = input.ReadInt32();
            break;
          }
          case 16: {
            Price = input.ReadInt32();
            break;
          }
          case 26: {
            ClientName = input.ReadString();
            break;
          }
          case 32: {
            NumberOfSeats = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MatchID = input.ReadInt32();
            break;
          }
          case 16: {
            Price = input.ReadInt32();
            break;
          }
          case 26: {
            ClientName = input.ReadString();
            break;
          }
          case 32: {
            NumberOfSeats = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Request : pb::IMessage<Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ClientServerWithJava.Networking.ProtocolReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request(Request other) : this() {
      requestType_ = other.requestType_;
      switch (other.DataCase) {
        case DataOneofCase.Userdto:
          Userdto = other.Userdto.Clone();
          break;
        case DataOneofCase.Username:
          Username = other.Username;
          break;
        case DataOneofCase.Filtru:
          Filtru = other.Filtru;
          break;
        case DataOneofCase.IdUser:
          IdUser = other.IdUser;
          break;
        case DataOneofCase.Ticketdto:
          Ticketdto = other.Ticketdto.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request Clone() {
      return new Request(this);
    }

    /// <summary>Field number for the "request_type" field.</summary>
    public const int RequestTypeFieldNumber = 1;
    private global::ClientServerWithJava.Networking.Request.Types.RequestType requestType_ = global::ClientServerWithJava.Networking.Request.Types.RequestType.Login;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClientServerWithJava.Networking.Request.Types.RequestType RequestType {
      get { return requestType_; }
      set {
        requestType_ = value;
      }
    }

    /// <summary>Field number for the "userdto" field.</summary>
    public const int UserdtoFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClientServerWithJava.Networking.UserDTO Userdto {
      get { return dataCase_ == DataOneofCase.Userdto ? (global::ClientServerWithJava.Networking.UserDTO) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Userdto;
      }
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Username {
      get { return HasUsername ? (string) data_ : ""; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        dataCase_ = DataOneofCase.Username;
      }
    }
    /// <summary>Gets whether the "username" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUsername {
      get { return dataCase_ == DataOneofCase.Username; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "username" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUsername() {
      if (HasUsername) {
        ClearData();
      }
    }

    /// <summary>Field number for the "filtru" field.</summary>
    public const int FiltruFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Filtru {
      get { return HasFiltru ? (string) data_ : ""; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        dataCase_ = DataOneofCase.Filtru;
      }
    }
    /// <summary>Gets whether the "filtru" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFiltru {
      get { return dataCase_ == DataOneofCase.Filtru; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "filtru" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFiltru() {
      if (HasFiltru) {
        ClearData();
      }
    }

    /// <summary>Field number for the "idUser" field.</summary>
    public const int IdUserFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int IdUser {
      get { return HasIdUser ? (int) data_ : 0; }
      set {
        data_ = value;
        dataCase_ = DataOneofCase.IdUser;
      }
    }
    /// <summary>Gets whether the "idUser" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasIdUser {
      get { return dataCase_ == DataOneofCase.IdUser; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "idUser" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearIdUser() {
      if (HasIdUser) {
        ClearData();
      }
    }

    /// <summary>Field number for the "ticketdto" field.</summary>
    public const int TicketdtoFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClientServerWithJava.Networking.BuyTicketsDTO Ticketdto {
      get { return dataCase_ == DataOneofCase.Ticketdto ? (global::ClientServerWithJava.Networking.BuyTicketsDTO) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Ticketdto;
      }
    }

    private object data_;
    /// <summary>Enum of possible cases for the "data" oneof.</summary>
    public enum DataOneofCase {
      None = 0,
      Userdto = 2,
      Username = 3,
      Filtru = 4,
      IdUser = 5,
      Ticketdto = 6,
    }
    private DataOneofCase dataCase_ = DataOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataOneofCase DataCase {
      get { return dataCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearData() {
      dataCase_ = DataOneofCase.None;
      data_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RequestType != other.RequestType) return false;
      if (!object.Equals(Userdto, other.Userdto)) return false;
      if (Username != other.Username) return false;
      if (Filtru != other.Filtru) return false;
      if (IdUser != other.IdUser) return false;
      if (!object.Equals(Ticketdto, other.Ticketdto)) return false;
      if (DataCase != other.DataCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RequestType != global::ClientServerWithJava.Networking.Request.Types.RequestType.Login) hash ^= RequestType.GetHashCode();
      if (dataCase_ == DataOneofCase.Userdto) hash ^= Userdto.GetHashCode();
      if (HasUsername) hash ^= Username.GetHashCode();
      if (HasFiltru) hash ^= Filtru.GetHashCode();
      if (HasIdUser) hash ^= IdUser.GetHashCode();
      if (dataCase_ == DataOneofCase.Ticketdto) hash ^= Ticketdto.GetHashCode();
      hash ^= (int) dataCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RequestType != global::ClientServerWithJava.Networking.Request.Types.RequestType.Login) {
        output.WriteRawTag(8);
        output.WriteEnum((int) RequestType);
      }
      if (dataCase_ == DataOneofCase.Userdto) {
        output.WriteRawTag(18);
        output.WriteMessage(Userdto);
      }
      if (HasUsername) {
        output.WriteRawTag(26);
        output.WriteString(Username);
      }
      if (HasFiltru) {
        output.WriteRawTag(34);
        output.WriteString(Filtru);
      }
      if (HasIdUser) {
        output.WriteRawTag(40);
        output.WriteInt32(IdUser);
      }
      if (dataCase_ == DataOneofCase.Ticketdto) {
        output.WriteRawTag(50);
        output.WriteMessage(Ticketdto);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RequestType != global::ClientServerWithJava.Networking.Request.Types.RequestType.Login) {
        output.WriteRawTag(8);
        output.WriteEnum((int) RequestType);
      }
      if (dataCase_ == DataOneofCase.Userdto) {
        output.WriteRawTag(18);
        output.WriteMessage(Userdto);
      }
      if (HasUsername) {
        output.WriteRawTag(26);
        output.WriteString(Username);
      }
      if (HasFiltru) {
        output.WriteRawTag(34);
        output.WriteString(Filtru);
      }
      if (HasIdUser) {
        output.WriteRawTag(40);
        output.WriteInt32(IdUser);
      }
      if (dataCase_ == DataOneofCase.Ticketdto) {
        output.WriteRawTag(50);
        output.WriteMessage(Ticketdto);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RequestType != global::ClientServerWithJava.Networking.Request.Types.RequestType.Login) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) RequestType);
      }
      if (dataCase_ == DataOneofCase.Userdto) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Userdto);
      }
      if (HasUsername) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (HasFiltru) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Filtru);
      }
      if (HasIdUser) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IdUser);
      }
      if (dataCase_ == DataOneofCase.Ticketdto) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Ticketdto);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Request other) {
      if (other == null) {
        return;
      }
      if (other.RequestType != global::ClientServerWithJava.Networking.Request.Types.RequestType.Login) {
        RequestType = other.RequestType;
      }
      switch (other.DataCase) {
        case DataOneofCase.Userdto:
          if (Userdto == null) {
            Userdto = new global::ClientServerWithJava.Networking.UserDTO();
          }
          Userdto.MergeFrom(other.Userdto);
          break;
        case DataOneofCase.Username:
          Username = other.Username;
          break;
        case DataOneofCase.Filtru:
          Filtru = other.Filtru;
          break;
        case DataOneofCase.IdUser:
          IdUser = other.IdUser;
          break;
        case DataOneofCase.Ticketdto:
          if (Ticketdto == null) {
            Ticketdto = new global::ClientServerWithJava.Networking.BuyTicketsDTO();
          }
          Ticketdto.MergeFrom(other.Ticketdto);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RequestType = (global::ClientServerWithJava.Networking.Request.Types.RequestType) input.ReadEnum();
            break;
          }
          case 18: {
            global::ClientServerWithJava.Networking.UserDTO subBuilder = new global::ClientServerWithJava.Networking.UserDTO();
            if (dataCase_ == DataOneofCase.Userdto) {
              subBuilder.MergeFrom(Userdto);
            }
            input.ReadMessage(subBuilder);
            Userdto = subBuilder;
            break;
          }
          case 26: {
            Username = input.ReadString();
            break;
          }
          case 34: {
            Filtru = input.ReadString();
            break;
          }
          case 40: {
            IdUser = input.ReadInt32();
            break;
          }
          case 50: {
            global::ClientServerWithJava.Networking.BuyTicketsDTO subBuilder = new global::ClientServerWithJava.Networking.BuyTicketsDTO();
            if (dataCase_ == DataOneofCase.Ticketdto) {
              subBuilder.MergeFrom(Ticketdto);
            }
            input.ReadMessage(subBuilder);
            Ticketdto = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RequestType = (global::ClientServerWithJava.Networking.Request.Types.RequestType) input.ReadEnum();
            break;
          }
          case 18: {
            global::ClientServerWithJava.Networking.UserDTO subBuilder = new global::ClientServerWithJava.Networking.UserDTO();
            if (dataCase_ == DataOneofCase.Userdto) {
              subBuilder.MergeFrom(Userdto);
            }
            input.ReadMessage(subBuilder);
            Userdto = subBuilder;
            break;
          }
          case 26: {
            Username = input.ReadString();
            break;
          }
          case 34: {
            Filtru = input.ReadString();
            break;
          }
          case 40: {
            IdUser = input.ReadInt32();
            break;
          }
          case 50: {
            global::ClientServerWithJava.Networking.BuyTicketsDTO subBuilder = new global::ClientServerWithJava.Networking.BuyTicketsDTO();
            if (dataCase_ == DataOneofCase.Ticketdto) {
              subBuilder.MergeFrom(Ticketdto);
            }
            input.ReadMessage(subBuilder);
            Ticketdto = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Request message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum RequestType {
        [pbr::OriginalName("LOGIN")] Login = 0,
        [pbr::OriginalName("LOGOUT")] Logout = 1,
        [pbr::OriginalName("SIGNUP")] Signup = 2,
        [pbr::OriginalName("GET_MATCHES")] GetMatches = 3,
        [pbr::OriginalName("BUY_TICKETS")] BuyTickets = 4,
        [pbr::OriginalName("GET_MATCH")] GetMatch = 5,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Response : pb::IMessage<Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ClientServerWithJava.Networking.ProtocolReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response(Response other) : this() {
      responseType_ = other.responseType_;
      error_ = other.error_;
      userdto_ = other.userdto_ != null ? other.userdto_.Clone() : null;
      matchdto_ = other.matchdto_ != null ? other.matchdto_.Clone() : null;
      matches_ = other.matches_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response Clone() {
      return new Response(this);
    }

    /// <summary>Field number for the "response_type" field.</summary>
    public const int ResponseTypeFieldNumber = 1;
    private global::ClientServerWithJava.Networking.Response.Types.ResponseType responseType_ = global::ClientServerWithJava.Networking.Response.Types.ResponseType.Ok;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClientServerWithJava.Networking.Response.Types.ResponseType ResponseType {
      get { return responseType_; }
      set {
        responseType_ = value;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private string error_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "userdto" field.</summary>
    public const int UserdtoFieldNumber = 3;
    private global::ClientServerWithJava.Networking.UserDTO userdto_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClientServerWithJava.Networking.UserDTO Userdto {
      get { return userdto_; }
      set {
        userdto_ = value;
      }
    }

    /// <summary>Field number for the "matchdto" field.</summary>
    public const int MatchdtoFieldNumber = 4;
    private global::ClientServerWithJava.Networking.MatchDTO matchdto_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClientServerWithJava.Networking.MatchDTO Matchdto {
      get { return matchdto_; }
      set {
        matchdto_ = value;
      }
    }

    /// <summary>Field number for the "matches" field.</summary>
    public const int MatchesFieldNumber = 5;
    private static readonly pb::FieldCodec<string> _repeated_matches_codec
        = pb::FieldCodec.ForString(42);
    private readonly pbc::RepeatedField<string> matches_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Matches {
      get { return matches_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResponseType != other.ResponseType) return false;
      if (Error != other.Error) return false;
      if (!object.Equals(Userdto, other.Userdto)) return false;
      if (!object.Equals(Matchdto, other.Matchdto)) return false;
      if(!matches_.Equals(other.matches_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ResponseType != global::ClientServerWithJava.Networking.Response.Types.ResponseType.Ok) hash ^= ResponseType.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      if (userdto_ != null) hash ^= Userdto.GetHashCode();
      if (matchdto_ != null) hash ^= Matchdto.GetHashCode();
      hash ^= matches_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ResponseType != global::ClientServerWithJava.Networking.Response.Types.ResponseType.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ResponseType);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      if (userdto_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Userdto);
      }
      if (matchdto_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Matchdto);
      }
      matches_.WriteTo(output, _repeated_matches_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ResponseType != global::ClientServerWithJava.Networking.Response.Types.ResponseType.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ResponseType);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      if (userdto_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Userdto);
      }
      if (matchdto_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Matchdto);
      }
      matches_.WriteTo(ref output, _repeated_matches_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ResponseType != global::ClientServerWithJava.Networking.Response.Types.ResponseType.Ok) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ResponseType);
      }
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      if (userdto_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Userdto);
      }
      if (matchdto_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Matchdto);
      }
      size += matches_.CalculateSize(_repeated_matches_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Response other) {
      if (other == null) {
        return;
      }
      if (other.ResponseType != global::ClientServerWithJava.Networking.Response.Types.ResponseType.Ok) {
        ResponseType = other.ResponseType;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      if (other.userdto_ != null) {
        if (userdto_ == null) {
          Userdto = new global::ClientServerWithJava.Networking.UserDTO();
        }
        Userdto.MergeFrom(other.Userdto);
      }
      if (other.matchdto_ != null) {
        if (matchdto_ == null) {
          Matchdto = new global::ClientServerWithJava.Networking.MatchDTO();
        }
        Matchdto.MergeFrom(other.Matchdto);
      }
      matches_.Add(other.matches_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ResponseType = (global::ClientServerWithJava.Networking.Response.Types.ResponseType) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            if (userdto_ == null) {
              Userdto = new global::ClientServerWithJava.Networking.UserDTO();
            }
            input.ReadMessage(Userdto);
            break;
          }
          case 34: {
            if (matchdto_ == null) {
              Matchdto = new global::ClientServerWithJava.Networking.MatchDTO();
            }
            input.ReadMessage(Matchdto);
            break;
          }
          case 42: {
            matches_.AddEntriesFrom(input, _repeated_matches_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ResponseType = (global::ClientServerWithJava.Networking.Response.Types.ResponseType) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            if (userdto_ == null) {
              Userdto = new global::ClientServerWithJava.Networking.UserDTO();
            }
            input.ReadMessage(Userdto);
            break;
          }
          case 34: {
            if (matchdto_ == null) {
              Matchdto = new global::ClientServerWithJava.Networking.MatchDTO();
            }
            input.ReadMessage(Matchdto);
            break;
          }
          case 42: {
            matches_.AddEntriesFrom(ref input, _repeated_matches_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Response message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum ResponseType {
        [pbr::OriginalName("OK")] Ok = 0,
        [pbr::OriginalName("ERROR")] Error = 1,
        [pbr::OriginalName("UPDATE")] Update = 2,
        [pbr::OriginalName("GET_MATCHES")] GetMatches = 3,
        [pbr::OriginalName("GET_MATCH")] GetMatch = 4,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
